bplotJetProbe(){
 
  bool NoRes=false;
  TFile * fileMC = TFile::Open("MCPPbakPu3PFJetSpectraCombineTriggerJetPtNoJetIDCutTrkCorr.root","read");
  //if(NoRes)TFile * fileDATA = TFile::Open("DATAPPbakPu3PFJetSpectraCombineTriggerJetPtNoJetIDCutNoResidualTrkCorrCombined.root","read");
  //else TFile * fileDATA = TFile::Open("DATAPPbakPu3PFJetSpectraCombineTriggerJetPtNoJetIDCutProbleResidualCorrOnly.root","read");
  TFile * fileDATA = TFile::Open("DATAPPbakPu3PFJetSpectraCombineTriggerJetPtNoJetIDCutNoResidualTrkCorrCombined.root","read");
  TH2D *h2MCmid, *h2DATAmid, *h2MCforward, *h2DATAforward;
  h2MCmid = (TH2D)fileMC->Get("AvgPtBalanceMid");
  h2MCforward = (TH2D)fileMC->Get("AvgPtBalanceForward");
  h2DATAmid = (TH2D)fileDATA->Get("AvgPtBalanceMid");
  h2DATAforward = (TH2D)fileDATA->Get("AvgPtBalanceForward");

  TProfile *ProbeEtaMeanBDATA;
  ProbeEtaMeanBDATA = (TProfile*)fileDATA->Get("ProbeEtaMeanB");
  //TFile * fileDATAcorr = TFile::Open("DATAPPbakPu3PFJetSpectraCombineTriggerJetPtNoJetIDCutProbleResidualCorrOnly.root","read");
  TFile * fileDATAcorr = TFile::Open("DATAPPbakPu3PFJetSpectraCombineTriggerJetPtNoJetIDCutTrkCorrCombined.root","read");
  TProfile *ProbeEtaMeanBDATAcorr;
  ProbeEtaMeanBDATAcorr = (TProfile*)fileDATAcorr->Get("ProbeEtaMeanB");

  TFile * fileDATAmc = TFile::Open("MCPPbakPu3PFJetSpectraCombineTriggerJetPtNoJetIDCutTrkCorr.root","read");
  TProfile *ProbeEtaMeanBDATAmc;
  ProbeEtaMeanBDATAmc = (TProfile*)fileDATAmc->Get("ProbeEtaMeanB");

/*
  TProfile *ProbeEtaMeanBDATAmc;
  ProbeEtaMeanBDATAmc = (TProfile*)fileDATAmc->Get("ProbeEtaMeanB");
*/
  //ProbeEtaMeanBDATA->Rebin(30);
  //ProbeEtaMeanBDATA->Draw();
  //TH1D *sum = ProbeEtaMeanBDATA->ProjectionX();
  //sum->Draw();
  //for(int i=0; i<600; i++) cout<<endl<<ProbeEtaMeanBDATA->GetBinEntries(i+1)<<endl;

  int xmin=100;
  int xmax=140;
  TH1D* h1MCmid = h2MCmid->ProjectionY("h1MCmid",xmin,xmax);
  TH1D* h1MCforward = h2MCforward->ProjectionY("h1MCforward",xmin,xmax);
  TH1D* h1DATAmid = h2DATAmid->ProjectionY("h1DATAmid",xmin,xmax);
  TH1D* h1DATAforward = h2DATAforward->ProjectionY("h1DATAforward",xmin,xmax);

  const int neta=24;
  double etacut[neta+1]={-3, -2.6, -2.2, -1.9, -1.6, -1.4, -1.2, -1.0, -0.8, -0.6, -0.4, -0.2, 0, 
                   0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.9, 2.2, 2.6, 3.0};  
  ProbeEtaMeanBDATA->Rebin(24, "ProbeEtaMeanBDATAnew",etacut);
  ProbeEtaMeanBDATAcorr->Rebin(24, "ProbeEtaMeanBDATAnewcorr",etacut);
  ProbeEtaMeanBDATAmc->Rebin(24, "ProbeEtaMeanBDATAnewmc",etacut);
  //ProbeEtaMeanBDATAnew->Draw();
  double xEta[neta], yB[neta], yBerr[neta];  
  double yR[neta], yRerr[neta];
  double xEtac[neta], yBc[neta], yBcerr[neta];
  double yRc[neta], yRcerr[neta];
  double xEtamc[neta], yBmc[neta], yBmcerr[neta];
  double yRmc[neta], yRmcerr[neta];
  double datamc[neta], datamcerr[neta];
  double datacorrmc[neta], datacorrmcerr[neta];
  for(int i=0; i<neta; i++){
    xEta[i]=ProbeEtaMeanBDATAnew->GetBinCenter(i+1);
    yB[i]=ProbeEtaMeanBDATAnew->GetBinContent(i+1);
    yBerr[i]=ProbeEtaMeanBDATAnew->GetBinError(i+1);
    yR[i]=(2+yB[i])/(2-yB[i]);
    yRerr[i]=4*yBerr[i]/(2-yB[i])/(2-yB[i]);
    //cout<<xEta[i]<<"  "<<yR[i]<<"  "<<yRerr[i]<<endl;
    xEtac[i]=ProbeEtaMeanBDATAnewcorr->GetBinCenter(i+1);
    yBc[i]=ProbeEtaMeanBDATAnewcorr->GetBinContent(i+1);
    yBcerr[i]=ProbeEtaMeanBDATAnewcorr->GetBinError(i+1);
    yRc[i]=(2+yBc[i])/(2-yBc[i]);
    yRcerr[i]=4*yBcerr[i]/(2-yBc[i])/(2-yBc[i]);
    //cout<<xEta[i]<<"  "<<yR[i]<<"  "<<yRerr[i]<<endl;
    xEtamc[i]=ProbeEtaMeanBDATAnewmc->GetBinCenter(i+1);
    yBmc[i]=ProbeEtaMeanBDATAnewmc->GetBinContent(i+1);
    yBmcerr[i]=ProbeEtaMeanBDATAnewmc->GetBinError(i+1);
    yRmc[i]=(2+yBmc[i])/(2-yBmc[i]);
    yRmcerr[i]=4*yBmcerr[i]/(2-yBmc[i])/(2-yBmc[i]);
 
    datamc[i]=yR[i]/yRmc[i];
    datamcerr[i]=datamc[i]*sqrt(yRerr[i]*yRerr[i]/yR[i]/yR[i] + yRmcerr[i]*yRmcerr[i]/yRmc[i]/yRmc[i]);
    datacorrmc[i]=yRc[i]/yRmc[i];
    datacorrmcerr[i]=datacorrmc[i]*sqrt(yRcerr[i]*yRcerr[i]/yRc[i]/yRc[i] + yRmcerr[i]*yRmcerr[i]/yRmc[i]/yRmc[i]);
  }

  //h1MCmid->Rebin(4);
  //h1MCforward->Rebin(4);
  //h1DATAmid->Rebin(4);
  //h1DATAforward->Rebin(4);
  //cout<<h1MCmid->FindBin(-1)<<"  "<<h1MCmid->FindBin(1)<<endl;
  //h1MCmid->GetXaxis()->GetNbins()
  h1MCmid->Scale(1.0/h1MCmid->Integral(h1MCmid->FindBin(-1),h1MCmid->FindBin(1)));
  h1MCforward->Scale(1.0/h1MCforward->Integral(h1MCmid->FindBin(-1),h1MCmid->FindBin(1)));
  h1DATAmid->Scale(1.0/h1DATAmid->Integral(h1MCmid->FindBin(-1),h1MCmid->FindBin(1)));
  h1DATAforward->Scale(1.0/h1DATAforward->Integral(h1MCmid->FindBin(-1),h1MCmid->FindBin(1)));

  TCanvas *c2 = new TCanvas("c2","c2",3,2,899,439);
  c2->SetFillColor(10);
  c2->SetFrameFillColor(0);
  c2->SetFrameBorderSize(0);
  c2->SetFrameBorderMode(0);
  c2->SetLeftMargin(0.17);
  c2->SetBottomMargin(0.14);
  c2->SetTopMargin(0.1);
  c2->SetRightMargin(0.02);
  c2->Divide(2,1);
  c2->SetTicks(-1);
 gStyle->SetOptStat(0);

  c2->cd(1);
 gPad->SetTicks(-1);
 gPad->SetLeftMargin(0.17);
 gPad->SetBottomMargin(0.14);
 gPad->SetTopMargin(0.02);
 gPad->SetRightMargin(0.02);
 TH1D* hist = new TH1D("hist","",120,-3,3.);
 hist->SetTitle("");
 hist->SetXTitle("#eta_{probe}");
 hist->SetYTitle("Relative Response");
 //hist->GetXaxis()->SetRangeUser(-0.999, 0.999);
 hist->SetMinimum(0.75);
 hist->SetMaximum(1.25);
 hist->GetXaxis()->CenterTitle(1);
 hist->GetYaxis()->CenterTitle(1);
 hist->GetYaxis()->SetTitleOffset(1.45);
 hist->GetXaxis()->SetTitleOffset(1.15);
 hist->GetXaxis()->SetTitleSize(0.056);
 hist->GetYaxis()->SetTitleSize(0.056);
 hist->GetXaxis()->SetLabelSize(0.05);
 hist->GetYaxis()->SetLabelSize(0.05);
 //hist->GetXaxis()->SetNdivisions(506);
 //hist->GetYaxis()->SetNdivisions(506);
 //hist->SetFillColor(kRed-9);
 //hist->SetLineColor(1);
 hist->Draw();
 //hist->Draw("psame");
  TGraphErrors *gr1= new TGraphErrors(neta, xEta, yR, 0, yRerr);
  gr1->SetMarkerStyle(20);
  gr1->SetMarkerColor(1);
  gr1->SetLineColor(1);
  gr1->SetLineStyle(1);
  gr1->SetLineWidth(2);
  gr1->SetMarkerSize(1.0);
  //gr1->Draw("psameEZ");
  TGraphErrors *gr2= new TGraphErrors(neta, xEtac, yRc, 0, yRcerr);
  gr2->SetMarkerStyle(24);
  gr2->SetMarkerColor(4);
  gr2->SetLineColor(4);
  gr2->SetLineStyle(1);
  gr2->SetLineWidth(2);
  gr2->SetMarkerSize(1.0);
  //gr2->Draw("psameEZ");
  TGraphErrors *gr3= new TGraphErrors(neta, xEtamc, yRmc, 0, yRmcerr);
  gr3->SetMarkerStyle(21);
  gr3->SetMarkerColor(2);
  gr3->SetLineColor(2);
  gr3->SetLineStyle(1);
  gr3->SetLineWidth(2);
  gr3->SetMarkerSize(1.0);
  gr3->Draw("psameEZ");
  gr1->Draw("psameEZ");
  gr2->Draw("psameEZ");
    TLegend *leg0 = new TLegend(0.56,0.75,0.83,0.94);
    leg0->SetFillColor(10);
    leg0->SetBorderSize(0.05);
    leg0->SetTextFont(43);
    leg0->SetTextSize(18.0);
    leg0->AddEntry(gr1,"uncorrected","p");
    leg0->AddEntry(gr2,"corrected","p");
    leg0->AddEntry(gr3,"PYTHIA+HIJING","p");
    leg0->Draw();
    TLatex *tex = new TLatex(-2.7,1.20,"Anti-k_{T} PF R=0.3");
    tex->SetTextFont(42);
    tex->SetTextSize(0.043);
    tex->SetLineWidth(2);
    tex->Draw();
    TLatex *tex = new TLatex(-2.7,1.16,"|#eta_{jet ref}|<1.3");
    tex->SetTextFont(42);
    tex->SetTextSize(0.043);
    tex->SetLineWidth(2);
    tex->Draw();
    TLatex *tex = new TLatex(-2.7,1.13,"|#phi_{1,2}|>2.5");
    tex->SetTextFont(42);
    tex->SetTextSize(0.043);
    tex->SetLineWidth(2);
    //tex->Draw();
    TLatex *tex = new TLatex(-2.7,1.10,"p_{T}^{avg} > 100 GeV/c");
    tex->SetTextFont(42);
    tex->SetTextSize(0.043);
    tex->SetLineWidth(2);
    tex->Draw();

  c2->cd(2);
 gPad->SetTicks(-1);
 gPad->SetLeftMargin(0.17);
 gPad->SetBottomMargin(0.14);
 gPad->SetTopMargin(0.02);
 gPad->SetRightMargin(0.02);
 TH1D* hist = new TH1D("hist","",120,-3,3.);
 hist->SetTitle("");
 hist->SetXTitle("#eta_{probe}");
 hist->SetYTitle("Data/MC");
 //hist->GetXaxis()->SetRangeUser(-0.999, 0.999);
 hist->SetMinimum(0.75);
 hist->SetMaximum(1.25);
 hist->GetXaxis()->CenterTitle(1);
 hist->GetYaxis()->CenterTitle(1);
 hist->GetYaxis()->SetTitleOffset(1.45);
 hist->GetXaxis()->SetTitleOffset(1.15);
 hist->GetXaxis()->SetTitleSize(0.056);
 hist->GetYaxis()->SetTitleSize(0.056);
 hist->GetXaxis()->SetLabelSize(0.05);
 hist->GetYaxis()->SetLabelSize(0.05);
 //hist->GetXaxis()->SetNdivisions(506);
 //hist->GetYaxis()->SetNdivisions(506);
 //hist->SetFillColor(kRed-9);
 //hist->SetLineColor(1);
 hist->Draw();
 //hist->Draw("psame");
  double datamc[neta], datamcerr[neta];
  double datacorrmc[neta], datacorrmcerr[neta];
  TGraphErrors *gr1= new TGraphErrors(neta, xEta, datamc, 0, datamcerr);
  gr1->SetMarkerStyle(20);
  gr1->SetMarkerColor(1);
  gr1->SetLineColor(1);
  gr1->SetLineStyle(1);
  gr1->SetLineWidth(2);
  gr1->SetMarkerSize(1.0);
  gr1->Draw("psameEZ");
  TGraphErrors *gr2= new TGraphErrors(neta, xEtac, datacorrmc, 0, datacorrmcerr);
  gr2->SetMarkerStyle(24);
  gr2->SetMarkerColor(4);
  gr2->SetLineColor(4);
  gr2->SetLineStyle(1);
  gr2->SetLineWidth(2);
  gr2->SetMarkerSize(1.0);
  gr2->Draw("psameEZ");
    TLegend *leg0 = new TLegend(0.59,0.75,0.86,0.94);
    leg0->SetFillColor(10);
    leg0->SetBorderSize(0.05);
    leg0->SetTextFont(43);
    leg0->SetTextSize(20.0);
    leg0->AddEntry(gr1,"uncorrected","p");
    leg0->AddEntry(gr2,"corrected","p");
    leg0->Draw();
    TLatex *tex = new TLatex(-2.7,1.2,"Anti-k_{T} PF R=0.3");
    tex->SetTextFont(42);
    tex->SetTextSize(0.043);
    tex->SetLineWidth(2);
    tex->Draw();
    TLatex *tex = new TLatex(-2.7,1.16,"|#eta_{jet ref}|<1.3");
    tex->SetTextFont(42);
    tex->SetTextSize(0.043);
    tex->SetLineWidth(2);
    tex->Draw();
    TLatex *tex = new TLatex(-2.7,1.13,"|#phi_{1,2}|>2.5");
    tex->SetTextFont(42);
    tex->SetTextSize(0.043);
    tex->SetLineWidth(2);
    //tex->Draw();
    TLatex *tex = new TLatex(-2.7,1.10,"p_{T}^{avg} > 100 GeV/c");
    tex->SetTextFont(42);
    tex->SetTextSize(0.043);
    tex->SetLineWidth(2);
    tex->Draw();
    TLine *line =new TLine(-3, 1, 3, 1);
    line->SetLineWidth(2);
    line->Draw();

    c2->SaveAs("hin14001etaprobeclosure.gif");

}

