plotDiJetBalance(){
 
  bool NoRes=false;
  TFile * fileMC = TFile::Open("MCPPbakPu3PFJetSpectraCombineTriggerJetPtNoJetIDCutTrkCorr.root","read");
  if(NoRes)TFile * fileDATA = TFile::Open("DATAPPbakPu3PFJetSpectraCombineTriggerJetPtNoJetIDCutNoResidualTrkCorrCombined.root","read");
  //else TFile * fileDATA = TFile::Open("DATAPPbakPu3PFJetSpectraCombineTriggerJetPtNoJetIDCutProbleResidualCorrOnly.root","read");
  else TFile * fileDATA = TFile::Open("DATAPPbakPu3PFJetSpectraCombineTriggerJetPtNoJetIDCutTrkCorrCombined.root","read");
  TH2D *h2MCmid, *h2DATAmid, *h2MCforward, *h2DATAforward;
  h2MCmid = (TH2D)fileMC->Get("AvgPtBalanceMid");
  h2MCforward = (TH2D)fileMC->Get("AvgPtBalanceForward");
  h2DATAmid = (TH2D)fileDATA->Get("AvgPtBalanceMid");
  h2DATAforward = (TH2D)fileDATA->Get("AvgPtBalanceForward");

  int xmin=100;
  int xmax=140;
  TH1D* h1MCmid = h2MCmid->ProjectionY("h1MCmid",xmin,xmax);
  TH1D* h1MCforward = h2MCforward->ProjectionY("h1MCforward",xmin,xmax);
  TH1D* h1DATAmid = h2DATAmid->ProjectionY("h1DATAmid",xmin,xmax);
  TH1D* h1DATAforward = h2DATAforward->ProjectionY("h1DATAforward",xmin,xmax);

  //h1MCmid->Rebin(4);
  //h1MCforward->Rebin(4);
  //h1DATAmid->Rebin(4);
  //h1DATAforward->Rebin(4);
  //cout<<h1MCmid->FindBin(-1)<<"  "<<h1MCmid->FindBin(1)<<endl;
  //h1MCmid->GetXaxis()->GetNbins()
  h1MCmid->Scale(1.0/h1MCmid->Integral(h1MCmid->FindBin(-1),h1MCmid->FindBin(1)));
  h1MCforward->Scale(1.0/h1MCforward->Integral(h1MCmid->FindBin(-1),h1MCmid->FindBin(1)));
  h1DATAmid->Scale(1.0/h1DATAmid->Integral(h1MCmid->FindBin(-1),h1MCmid->FindBin(1)));
  h1DATAforward->Scale(1.0/h1DATAforward->Integral(h1MCmid->FindBin(-1),h1MCmid->FindBin(1)));

  TCanvas *c2 = new TCanvas("c2","c2",3,2,899,439);
  c2->SetFillColor(10);
  c2->SetFrameFillColor(0);
  c2->SetFrameBorderSize(0);
  c2->SetFrameBorderMode(0);
  c2->SetLeftMargin(0.17);
  c2->SetBottomMargin(0.14);
  c2->SetTopMargin(0.1);
  c2->SetRightMargin(0.02);
  c2->Divide(2,1);
  c2->SetTicks(-1);
 gStyle->SetOptStat(0);

  c2->cd(1);
 gPad->SetTicks(-1);
 gPad->SetLeftMargin(0.17);
 gPad->SetBottomMargin(0.14);
 gPad->SetTopMargin(0.02);
 gPad->SetRightMargin(0.02);
 h1MCmid->SetTitle("");
 h1MCmid->SetXTitle("Dijet Balance");
 h1MCmid->SetYTitle("Event Fraction");
 h1MCmid->GetXaxis()->SetRangeUser(-0.999, 0.999);
 h1MCmid->SetMinimum(-0.00001);
 //h1MCmid->SetMaximum(1.4*h1MCmid->GetMaximum());
 h1MCmid->SetMaximum(0.12);
 h1MCmid->GetXaxis()->CenterTitle(1);
 h1MCmid->GetYaxis()->CenterTitle(1);
 h1MCmid->GetYaxis()->SetTitleOffset(1.45);
 h1MCmid->GetXaxis()->SetTitleOffset(1.15);
 h1MCmid->GetXaxis()->SetTitleSize(0.056);
 h1MCmid->GetYaxis()->SetTitleSize(0.056);
 h1MCmid->GetXaxis()->SetLabelSize(0.05);
 h1MCmid->GetYaxis()->SetLabelSize(0.05);
 //h1MCmid->GetXaxis()->SetNdivisions(506);
 //h1MCmid->GetYaxis()->SetNdivisions(506);
 h1MCmid->SetFillColor(kRed-9);
 h1MCmid->SetLineColor(kRed-9);
 h1MCmid->SetMarkerColor(kRed-9);
 h1MCmid->Draw("hist");
 h1MCmid->Draw("psame");
 h1DATAmid->SetMarkerStyle(20);
 h1DATAmid->SetMarkerColor(1);
 h1DATAmid->SetLineColor(1);
 h1DATAmid->SetLineStyle(1);
 h1DATAmid->SetLineWidth(2);
 h1DATAmid->SetMarkerSize(1.0);
 h1DATAmid->Draw("psameEZ");
    TLegend *leg0 = new TLegend(0.52,0.67,0.89,0.76);
    leg0->SetFillColor(10);
    leg0->SetBorderSize(0.04);
    leg0->SetTextFont(43);
    leg0->SetTextSize(13.0);
    leg0->AddEntry(h1DATAmid,"pPb Data","pl");
    leg0->AddEntry(h1MCmid,"PYTHIA+HIJING","f");
    leg0->Draw();
    TLatex *tex = new TLatex(-0.1,0.109,"Anti-k_{T} R=0.3 PF Jet");
    tex->SetTextFont(42);
    tex->SetTextSize(0.043);
    tex->SetLineWidth(2);
    tex->Draw();
    TLatex *tex = new TLatex(-0.1,0.101,"100 < p_{T}^{avg} < 140 GeV/c");
    tex->SetTextFont(42);
    tex->SetTextSize(0.043);
    tex->SetLineWidth(2);
    tex->Draw();
    TLatex *tex = new TLatex(-0.1,0.093,"|#eta_{jet ref}|<1.3, |#eta_{jet probe}|<1.3");
    tex->SetTextFont(42);
    tex->SetTextSize(0.043);
    tex->SetLineWidth(2);
    tex->Draw();
    if(NoRes){
    TLatex *tex = new TLatex(-0.9,0.101,"No Residual Corr");
    tex->SetTextFont(42);
    tex->SetTextSize(0.043);
    tex->SetLineWidth(2);
    tex->Draw();
    }

  c2->cd(2);
 gPad->SetTicks(-1);
 gPad->SetLeftMargin(0.17);
 gPad->SetBottomMargin(0.14);
 gPad->SetTopMargin(0.02);
 gPad->SetRightMargin(0.02);
 h1MCforward->SetTitle("");
 h1MCforward->SetXTitle("Dijet Balance");
 h1MCforward->SetYTitle("Event Fraction");
 h1MCforward->GetXaxis()->SetRangeUser(-0.999, 0.999);
 h1MCforward->SetMinimum(-0.00001);
 //h1MCforward->SetMaximum(1.4*h1MCforward->GetMaximum());
 h1MCforward->SetMaximum(0.12);
 h1MCforward->GetXaxis()->CenterTitle(1);
 h1MCforward->GetYaxis()->CenterTitle(1);
 h1MCforward->GetYaxis()->SetTitleOffset(1.45);
 h1MCforward->GetXaxis()->SetTitleOffset(1.15);
 h1MCforward->GetXaxis()->SetTitleSize(0.056);
 h1MCforward->GetYaxis()->SetTitleSize(0.056);
 h1MCforward->GetXaxis()->SetLabelSize(0.05);
 h1MCforward->GetYaxis()->SetLabelSize(0.05);
 //h1MCforward->GetXaxis()->SetNdivisions(506);
 //h1MCforward->GetYaxis()->SetNdivisions(506);
 h1MCforward->SetFillColor(kRed-9);
 h1MCforward->SetLineColor(kRed-9);
 h1MCforward->SetMarkerColor(kRed-9);
 h1MCforward->Draw("hist");
 h1MCforward->Draw("psame");
 h1DATAforward->SetMarkerStyle(20);
 h1DATAforward->SetMarkerColor(1);
 h1DATAforward->SetLineColor(1);
 h1DATAforward->SetLineStyle(1);
 h1DATAforward->SetLineWidth(2);
 h1DATAforward->SetMarkerSize(1.0);
 h1DATAforward->Draw("psameEZ");
    TLegend *leg0 = new TLegend(0.52,0.67,0.89,0.76);
    leg0->SetFillColor(10);
    leg0->SetBorderSize(0.04);
    leg0->SetTextFont(43);
    leg0->SetTextSize(13.0);
    leg0->AddEntry(h1DATAforward,"pPb Data","pl");
    leg0->AddEntry(h1MCforward,"PYTHIA+HIJING","f");
    leg0->Draw();
    TLatex *tex = new TLatex(-0.1,0.109,"Anti-k_{T} R=0.3 PF Jet");
    tex->SetTextFont(42);
    tex->SetTextSize(0.043);
    tex->SetLineWidth(2);
    tex->Draw();
    TLatex *tex = new TLatex(-0.1,0.101,"100 < p_{T}^{avg} < 140 GeV/c");
    tex->SetTextFont(42);
    tex->SetTextSize(0.043);
    tex->SetLineWidth(2);
    tex->Draw();
    TLatex *tex = new TLatex(-0.1,0.093,"|#eta_{jet ref}|<1.3, |#eta_{jet probe}|>1.3");
    tex->SetTextFont(42);
    tex->SetTextSize(0.043);
    tex->SetLineWidth(2);
    tex->Draw();
    if(NoRes){
    TLatex *tex = new TLatex(-0.9,0.101,"No Residual Corr");
    tex->SetTextFont(42);
    tex->SetTextSize(0.043);
    tex->SetLineWidth(2);
    tex->Draw();
    }

    if(NoRes) c2->SaveAs("hin14001DiJetBalancept100140noRes.gif");
    else c2->SaveAs("hin14001DiJetBalancept100140.gif");

}

